#!/usr/bin/env amber

import {
    ends_with, join, lpad, parse_int, slice, split, split_words, trim
} from "std/text"
import { array_pop } from "std/array"

fun is_valid(orig_line: Text, is_p2: Bool): Bool? {
    // Recursion not yet supported... :/ recurse manually instead
    // Keep recursion call stack as array of strings
    // (nested arrays not supported)
    // (Unfortunately this means constantly casting between Text and Int)
    // e.g. ["123: 12 3"] -> ["12: 12", "41: 12", "120: 12"] etc.
    // (well, better to keep track of index... so)
    // ["123:1"] -> ["12:2", "41:2", "120:2"] etc.
    let parts = split(orig_line, ":")
    let target = parts[0]
    let val_strings = split_words(trim(parts[1]))
    let vals = [Int]
    for val_string in val_strings {
        vals += [parse_int(val_string)?]
    }
    let args = [target + ":" + ((len(vals) - 1) as Text)]
    while len(args) > 0 {
        let line = array_pop(args) failed {return false}
        // evidently the "while len(args) > 0" isn't enough...
        parts = split(line, ":")
        target = parts[0]
        let target_int = parse_int(target)?
        let index = parse_int(parts[1])?
        if index == 0 {
            if target_int == vals[0]:
                return true
        } else {
            let remaining = ":" + ((index - 1) as Text)
            let last = vals[index]
            if is_p2 and ends_with(target, (last as Text)):
                args = args + [
                    slice(target, 0, len(target)-len(last as Text))
                    + remaining
                ]
            if target_int % last == 0:
                args = args + [
                    ((target_int / last) as Text)
                    + remaining
                ]
            if target_int - last >= 0:
                args = args + [
                    ((target_int - last) as Text)
                    + remaining
                ]
            join(args, ",") // removing this makes the program fail???
        }
    }
    return false
}

main {
    let total_1 = 0
    let total_2 = 0
    for index, line in lines("input07.txt") {
        echo lpad(index as Text, " ", 3)+"/850 ("+line+")"
        if is_valid(line, false)?:
            total_1 += parse_int(split(line, ":")[0])?
        if is_valid(line, true)?:
            total_2 += parse_int(split(line, ":")[0])?
    }
    echo total_1
    echo total_2
}
